FIML: false

studies:
  eclsk2011_study1:
    data: study1
    models:
      theory:
        ATL: 
            - TKEEPS
            - TSHOWS
            - TWORKS
            - TADAPTS
            - TFOLLOW
            - TPERSIS
            - TATTEN
        CBQ_A:
            - TBEZDAC
            - TBNOFIN
            - TBGCCLR
            - TBGCBLD
            - TBABSBK
            - TBEZDSL
        CBQ_I:
            - TBWTTSK
            - TBTRBST
            - TBFLWIN
            - TBSTNO
      efa2occ124:
         F1:
            - TKEEPS
            - TSHOWS
            - TWORKS
            - TADAPTS
            - TFOLLOW
            - TPERSIS
            - TATTEN
            - TBEZDAC
            - TBNOFIN
            - TBEZDSL
            - TBWTTSK
            - TBTRBST
            - TBFLWIN
            - TBSTNO
         F2:
            - TBGCCLR
            - TBGCBLD
            - TBABSBK

      efa3occ1:
         F1:
            - TBSTNO
            - TBTRBST
            - TFOLLOW
            - TBWTTSK
            - TBEZDSL
            - TBFLWIN
            - TBEZDAC
         F2:
            - TWORKS
            - TPERSIS
            - TSHOWS
            - TADAPTS
            - TKEEPS
            - TATTEN
            - TBNOFIN
         F3:
            - TBGCCLR
            - TBGCBLD
            - TBABSBK
      efa3occ24:
         F1:
            - TBSTNO
            - TBTRBST
            - TFOLLOW
            - TBWTTSK
            - TBEZDSL
            - TBFLWIN
         F2:
            - TWORKS
            - TPERSIS
            - TSHOWS
            - TADAPTS
            - TKEEPS
            - TATTEN
            - TBNOFIN
         F3:
            - TBGCCLR
            - TBGCBLD
            - TBABSBK

      efa4occ12:
         F1:
            - TWORKS
            - TPERSIS
            - TSHOWS
            - TADAPTS
            - TKEEPS
            - TATTEN
         F2:
            - TBEZDSL
            - TBTRBST
            - TBEZDAC
            - TBNOFIN
         F3:
            - TBSTNO
            - TBWTTSK
            - TFOLLOW
            - TBFLWIN
         F4:
            - TBGCCLR
            - TBGCBLD
            - TBABSBK
      efa4occ4:
         F1:
            - TWORKS
            - TPERSIS
            - TSHOWS
            - TADAPTS
            - TATTEN
         F2:
            - TBEZDSL
            - TBTRBST
            - TBEZDAC
            - TBNOFIN
            - TKEEPS
         F3:
            - TBSTNO
            - TBWTTSK
            - TFOLLOW
            - TBFLWIN
         F4:
            - TBGCCLR
            - TBGCBLD
            - TBABSBK

      efa5occ1:
         F1:
            - TWORKS
            - TSHOWS
            - TPERSIS
            - TADAPTS
            - TATTEN
            - TKEEPS
         F2:
            - TBEZDSL
            - TBTRBST
         F3:
            - TBEZDAC
            - TBNOFIN
         F4:
            - TBSTNO
            - TBWTTSK
            - TFOLLOW
            - TBFLWIN
         F5:
            - TBGCCLR
            - TBGCBLD
            - TBABSBK

      efa5occ2:
         F1:
            - TSHOWS
            - TWORKS
            - TPERSIS
            - TADAPTS
            - TKEEPS
         F2:
            - TBEZDSL
            - TBTRBST
            - TATTEN
            - TBEZDAC
         F3:
            - TBNOFIN
         F4:
            - TBSTNO
            - TBWTTSK
            - TFOLLOW
            - TBFLWIN
         F5:
            - TBGCCLR
            - TBGCBLD
            - TBABSBK

      efa5occ4:
         F1:
            - TWORKS
            - TSHOWS
            - TPERSIS
            - TADAPTS
            - TATTEN
         F2:
            - TBEZDSL
            - TBTRBST
         F3:
            - TBEZDAC
            - TBNOFIN
            - TKEEPS
         F4:
            - TBSTNO
            - TBWTTSK
            - TFOLLOW
            - TBFLWIN
         F5:
            - TBGCCLR
            - TBGCBLD
            - TBABSBK
  eclsk2011_study2:
    data: study2
    models:
      efa2occ678:
         F1:
            - TPERSIS
            - TWORKS
            - TBEZDAC
            - TATTEN
            - TSHOWS
            - TBHTATN
            - TBDSATN
            - TBLKARO
            - TBPYATN
            - TBEZDSL
            - TBFLWIN
            - TBPLANS
            - TKEEPS
            - TADAPTS
         F2:
            - TBEZWAT
            - TBHTSLW
            - TBHTTLK
            - TBSPTLD
            - TBSPQIK
            - TFOLLOW
      efa3occ678:
         F1:
            - TBDSATN
            - TBHTATN
            - TBPYATN
            - TBLKARO
            - TBEZDAC
            - TBEZDSL
         F2:
            - TSHOWS
            - TPERSIS
            - TWORKS
            - TADAPTS
            - TATTEN
            - TBPLANS
            - TKEEPS
            - TBFLWIN
         F3:
            - TBEZWAT
            - TBHTSLW
            - TBHTTLK
            - TBSPTLD
            - TBSPQIK
            - TFOLLOW
      efa4occ6:
         F1:
            - TBDSATN
            - TBHTATN
            - TBPYATN
            - TBLKARO
            - TBEZDAC
            - TBEZDSL
         F2:
            - TSHOWS
            - TPERSIS
            - TWORKS
            - TADAPTS
            - TATTEN
            - TBPLANS
            - TKEEPS
            - TBFLWIN
         F3:
            - TBEZWAT
            - TBHTSLW
            - TBHTTLK
            - TBSPTLD
            - TFOLLOW
         F4:
            - TBSPQIK
      efa4occ78:
         F1:
            - TBDSATN
            - TBHTATN
            - TBPYATN
            - TBLKARO
            - TBEZDAC
            - TBEZDSL
         F2:
            - TSHOWS
            - TPERSIS
            - TWORKS
            - TADAPTS
            - TATTEN
            - TBPLANS
            - TKEEPS
            - TBFLWIN
         F3:
            - TBEZWAT
            - TBHTSLW
            - TBHTTLK
            - TFOLLOW
         F4:
            - TBSPQIK
            - TBSPTLD
      efa5occ678:
         F1:
            - TBDSATN
            - TBHTATN
            - TBPYATN
            - TBLKARO
            - TBEZDAC
            - TBEZDSL
         F2:
            - TSHOWS
            - TPERSIS
            - TWORKS
            - TADAPTS
            - TATTEN
            - TKEEPS
            - TBFLWIN
         F3:
            - TBEZWAT
            - TBHTSLW
            - TBHTTLK
            - TFOLLOW
         F4:
            - TBSPQIK
            - TBSPTLD
         F5:
            - TBPLANS
      theory:
        ATL:
            - TKEEPS
            - TSHOWS
            - TWORKS
            - TADAPTS
            - TFOLLOW
            - TPERSIS
            - TATTEN
        TCMQ_A:
            - TBEZDSL
            - TBEZDAC
            - TBLKARO
            - TBPYATN
            - TBHTATN
            - TBDSATN
        TMCQ_I:
            - TBSPTLD
            - TBSPQIK
            - TBEZWAT
            - TBHTTLK
            - TBPLANS
            - TBFLWIN
            - TBHTSLW

