FIML: true

studies:
  eclsk2011_study1:
    data: eclsk2011
    subset: study1
    split: test
    models:
      theory:
        ATL: [ TKEEPS, TSHOWS, TWORKS, TADAPTS, TFOLLOW, TPERSIS, TATTEN ]
        CBQ_A: [ TBEZDAC, TBNOFIN, TBGCCLR, TBGCBLD, TBABSBK, TBEZDSL ]
        CBQ_I: [ TBWTTSK, TBTRBST, TBFLWIN, TBSTNO ]

      efa2occ124:
         F1: [ TKEEPS, TSHOWS, TWORKS, TADAPTS, TFOLLOW, TPERSIS, TATTEN,
               TBEZDAC, TBNOFIN, TBEZDSL, TBWTTSK, TBTRBST, TBFLWIN, TBSTNO ]
         F2: [ TBGCCLR, TBGCBLD, TBABSBK]

      efa3occ1:
         F1: [ TBSTNO, TBTRBST, TFOLLOW, TBWTTSK, TBEZDSL, TBFLWIN, TBEZDAC, 
               TATTEN, TBNOFIN ]
         F2: [ TWORKS, TPERSIS, TSHOWS, TADAPTS, TKEEPS ]
         F3: [ TBGCCLR, TBGCBLD, TBABSBK ]

      efa3occ24:
         F1: [ TBSTNO, TBTRBST, TFOLLOW, TBWTTSK, TBEZDSL, TBFLWIN, TKEEPS ]
         F2: [ TWORKS, TPERSIS, TSHOWS, TATTEN, TBNOFIN, TADAPTS, TBEZDAC ]
         F3: [ TBGCCLR, TBGCBLD, TBABSBK ]

      efa4occ12:
         F1: [ TWORKS, TPERSIS, TSHOWS, TADAPTS, TKEEPS, TATTEN ]
         F2: [ TBEZDSL, TBTRBST, TBEZDAC, TBNOFIN ]
         F3: [ TBSTNO, TBWTTSK, TFOLLOW, TBFLWIN ]
         F4: [ TBGCCLR, TBGCBLD, TBABSBK ]

      efa4occ4:
         F1: [ TWORKS, TPERSIS, TSHOWS, TADAPTS, TATTEN ]
         F2: [ TBEZDSL, TBTRBST, TBEZDAC, TBNOFIN, TKEEPS ]
         F3: [ TBSTNO, TBWTTSK, TFOLLOW, TBFLWIN ]
         F4: [ TBGCCLR, TBGCBLD, TBABSBK ]
