---
title: "Measurement models for executive function"
author: "Kyle Husmann"
date: "March 25, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)

mmod_models <- function(studyname) {
  mmod_models <- Sys.glob(paste0('data/res/', studyname, '/*_model.rds')) %>%
                 map(read_rds) %>%
                 map(rlang::eval_tidy)
  names(mmod_models) <- map(mmod_models, 'name')
  mmod_models
}

mmod_results <- function(studyname) {
  mmod_results <- Sys.glob(paste0('data/res/', studyname, '/*_result.rds')) %>%
                  map(read_rds)
  names(mmod_results) <- map(mmod_results, 'modelName')
  mmod_results
}

mmod_fits <- function(mmod_results) {
  tibble(
    name=map_chr(mmod_results, 'modelName'),
    n=map_dbl(mmod_results, 'numObs'),
    chisq=map_dbl(mmod_results, 'Chi'),
    dof=map_dbl(mmod_results, 'ChiDoF'),
    `-2ll`=map_dbl(mmod_results, 'Minus2LogLikelihood'),
    aic=map_dbl(mmod_results, 'AIC.Mx'),
    bic=map_dbl(mmod_results, 'BIC.Mx'),
    rmsea=map_dbl(mmod_results, 'RMSEA'),
    cfi=map_dbl(mmod_results, 'CFI'),
    tli=map_dbl(mmod_results, 'TLI')
  )
}
```

```{r}
study1_models <- mmod_models('eclsk2011_study1')
study2_models <- mmod_models('eclsk2011_study2')
```

```{r}
study1_results <- mmod_results('eclsk2011_study1')
(study1_fits <- mmod_fits(study1_results))
```

```{r}
study1_fits %>%
  mutate(name = fct_relevel(name, 'theory', after=0)) %>%
  arrange(name) %>%
  extract(name, c('numFct', 'occ'), 'efa(.)occ(.+)') %>%
  mutate(occ = map_chr(str_split(occ, ''), str_c, collapse = ', ')) %>%
  mutate(occ = str_replace(occ, '1, 2, 4', 'All')) %>%
  mutate(occ = str_replace(occ, '1', 'Fall Kindergarten')) %>%
  mutate(occ = str_replace(occ, '2', 'Spring Kindergarten')) %>%
  mutate(occ = str_replace(occ, '4', 'Spring 1st Grade')) %>%
  mutate(numFct = replace_na(numFct, 3),
         occ = replace_na(occ, '-')) %>%
  mutate_at(vars(n:bic), ~sprintf('%0.0f', .)) %>%
  mutate_at(vars(rmsea:tli), ~sprintf('%0.3f', .)) %>%
  filter(numFct != '5') %>%
  select(-numFct) %>%
  rename(`Occasions With Same Structure (from training set)` = occ,
         `N` = n,
         `Chisq` = chisq,
         `df` = dof,
         `-2LL` = `-2ll`,
         `AIC` = aic,
         `BIC` = bic,
         rmsea = rmsea,
         cfi = cfi,
         tli = tli) %>%
  kable(booktabs=T, align=c('l', rep('l', 10)), escape=F) %>%
  kable_styling(latex_options = c('scale_down')) %>%
  row_spec(1, bold = T) %>%
  row_spec(5, bold = T) %>%
  group_rows(index=c('Theoretical Structure (3 Factors)' = 1,
                     'EFA 2 Factor' = 1,
                     'EFA 3 Factor' = 2,
                     'EFA 4 Factor' = 2), latex_gap_space='2em') %>%
  add_header_above(c(' ' = 1, 'MMOD Model Fit Statistics (on test set)' = 9))

```

```{r}
study2_results <- mmod_results('eclsk2011_study2')
(study2_fits <- mmod_fits(study2_results))
```

```{r}
measures_theory <- list(
  ATL = c('TKEEPS', 'TSHOWS', 'TWORKS', 'TADAPTS', 'TFOLLOW', 'TPERSIS', 'TATTEN'),
  CBQ_A = c('TBEZDAC', 'TBNOFIN', 'TBGCCLR', 'TBGCBLD', 'TBEZDSL', 'TBABSBK'),
  CBQ_I = c('TBWTTSK', 'TBTRBST', 'TBFLWIN', 'TBSTNO') # Omitting: 'TBPLNAC', 'TBAPRRK'
# Parent Items
    # ATL_P = c('PWRKFIN', 'PSHWINT', 'PCONCEN', 'PCHORES', 'PLEARN', 'PCREATV'),
# Child assessment
    # DCCS = c('XCSBGSC')
    # NREV = c('XNRSSCR')
)
```

```{r}
#mmod_theory <- mmodModel(measures_theory, 'theory', fiml=F)
#mmod_theory_res <- mxRun(mmod_theory)
#summary(mmod_theory_res)
```

```{r}
#cfa_theory <- map(occasions, ~cfaModel(measures_theory, paste0('theorycfa', .), ., fiml=T))
#names(cfa_theory) <- map(cfa_theory, 'name')
#cfa_theory_res <- map(cfa_theory, mxRun)
#map(cfa_theory_res, summary)
```