---
title: "ECLS-K Growth Model"
author: "Kyle Husmann"
date: "September 27, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lmerTest)
library(broom.mixed)
library(kableExtra)


data(eclsk2011)

df <- eclsk2011$study1 %>%
      filter(split == 'val') %>%
      filter_at(vars(TWORKS, TPERSIS, TSHOWS, TADAPTS, TKEEPS, TATTEN,
                            TBGCCLR, TBGCBLD, TBABSBK, TBEZDSL, TBTRBST, TBEZDAC, TBNOFIN,
                            TBSTNO, TBWTTSK, TFOLLOW, TBFLWIN), all_vars(!is.na(.))) %>%
      mutate(
#        TFOLLOW_sc = TFOLLOW,
#        TATTEN_sc = TATTEN,
        TFOLLOW_sc = TFOLLOW/4*7,
        TATTEN_sc = TATTEN/4*7
      ) %>%
      mutate(
         OATL_F1 = scale(rowMeans(cbind(TWORKS, TPERSIS, TSHOWS, TADAPTS, TKEEPS), na.rm=T)),
         OENG_F2 = scale(rowMeans(cbind(TBGCCLR, TBGCBLD, TBABSBK), na.rm=T)),
         OATTEN_F3 = scale(rowMeans(cbind(TBSTNO, 8-TBTRBST, TFOLLOW_sc, TBWTTSK, 8-TBEZDSL,
                                 TBFLWIN, 8-TBEZDAC, TATTEN_sc, 8-TBNOFIN), na.rm=T))
      ) %>%
      mutate(
        MATL_F1 = scale(rowMeans(cbind(TWORKS, TPERSIS, TSHOWS, TADAPTS, TKEEPS, TATTEN), na.rm=T)),
        MENG_F2 = scale(rowMeans(cbind(TBGCCLR, TBGCBLD, TBABSBK), na.rm=T)),
        MINHIB_F4 = scale(rowMeans(cbind(TBSTNO, TBWTTSK, TFOLLOW_sc, TBFLWIN), na.rm=T)),
        MATTEN_F3 = scale(rowMeans(cbind(8-TBEZDSL, 8-TBTRBST, 8-TBEZDAC, 8-TBNOFIN), na.rm=T))
      ) %>%
      mutate(
         PATL_F1 = scale(rowMeans(cbind(TWORKS, TSHOWS, TPERSIS, TADAPTS, TATTEN, TKEEPS), na.rm=T)),
         PENG_F2 = scale(rowMeans(cbind(TBGCCLR, TBGCBLD, TBABSBK), na.rm=T)),
         PINHIB_F4 = scale(rowMeans(cbind(TBSTNO, TBWTTSK, TFOLLOW_sc, TBFLWIN), na.rm=T)),
         PATTEN_F3 = scale(rowMeans(cbind(8-TBEZDAC, 8-TBNOFIN), na.rm=T)),
         PATTEN2_F5 = scale(rowMeans(cbind(8-TBEZDSL, 8-TBTRBST), na.rm=T))
      ) %>%
      mutate(
        XTCHAPP_F1 = scale(rowMeans(cbind(TWORKS, TPERSIS, TSHOWS, TADAPTS,
                                  TKEEPS, TATTEN, TFOLLOW), na.rm=T)),
        XATTNFS_F3 = scale(rowMeans(cbind(8-TBEZDAC, 8-TBNOFIN, 8-TBEZDSL,
                                  TBGCBLD, TBGCCLR, TBABSBK), na.rm=T)),
        XINBCNT_F4 = scale(rowMeans(cbind(8-TBTRBST, TBSTNO, TBWTTSK,
                                  TBFLWIN, TBPLNAC, TBAPRRK), na.rm=T)))
```

```{r}
df %>%
select(XATTNFS, XATTNFS_F3, TBEZDAC, TBNOFIN, TBEZDSL,
       TBGCBLD, TBGCCLR, TBABSBK) %>% 
filter(is.na(df$XATTNFS_F3) != is.na(df$XATTNFS))
```
```{r}
(sum(abs(df$XTCHAPP_F1 - df$XTCHAPP)>0.01, na.rm=T))
(sum(abs(df$XATTNFS_F3 - df$XATTNFS)>0.01, na.rm=T))
(sum(abs(df$XINBCNT_F4 - df$XINBCNT)>0.01, na.rm=T))

(sum(is.na(df$XTCHAPP_F1) != is.na(df$XTCHAPP)))
(sum(is.na(df$XATTNFS_F3) != is.na(df$XATTNFS)))
(sum(is.na(df$XINBCNT_F4) != is.na(df$XINBCNT)))

```
# Make models

```{r}
models_read <- list(
  theory = lmer(XRTHETK5 ~ grade + XATTNFS_F3 + XTCHAPP_F1 + XINBCNT_F4 + (1|CHILDID), df,
             REML=F, control=lmerControl(optimizer='bobyqa')),
  
  f3 = lmer(XRTHETK5 ~ grade + OATL_F1 + OENG_F2 + OATTEN_F3 + (1|CHILDID), df,
            REML=F, control=lmerControl(optimizer='bobyqa')),
  
  f4 = lmer(XRTHETK5 ~ grade + MATL_F1 + MENG_F2 + MINHIB_F4 + MATTEN_F3 + (1|CHILDID), df,
             REML=F, control=lmerControl(optimizer='bobyqa')),
  
  f5 = lmer(XRTHETK5 ~ grade + PATL_F1 + PENG_F2 + PINHIB_F4 + PATTEN_F3 + PATTEN2_F5 + (1|CHILDID), df,
             REML=F, control=lmerControl(optimizer='bobyqa'))
)

models_math <- list(
  theory = lmer(XMTHETK5 ~ grade + XATTNFS_F3 + XTCHAPP_F1 + XINBCNT_F4 + (1|CHILDID), df,
             REML=F, control=lmerControl(optimizer='bobyqa')),
  
  f3 = lmer(XMTHETK5 ~ grade + OATL_F1 + OENG_F2 + OATTEN_F3 + (1|CHILDID), df,
            REML=F, control=lmerControl(optimizer='bobyqa')),
  
  f4 = lmer(XMTHETK5 ~ grade + MATL_F1 + MENG_F2 + MINHIB_F4 + MATTEN_F3 + (1|CHILDID), df,
             REML=F, control=lmerControl(optimizer='bobyqa')),
  
  f5 = lmer(XMTHETK5 ~ grade + PATL_F1 + PENG_F2 + PINHIB_F4 + PATTEN_F3 + PATTEN2_F5 + (1|CHILDID), df,
             REML=F, control=lmerControl(optimizer='bobyqa')) 
)
```

```{r}
models <- tibble(
  type = c('read', 'math'),
  model = list(models_read, models_math),
  struct = map(model, names)
) %>%
  unnest(c(model, struct)) %>%
  mutate(id = str_c(type, struct, sep='.'),
         summary = map(model, summary),
         tdy = map(model, tidy, conf.int=T, conf.method='Wald', quiet=T),
         glnc = map(model, glance))

models_summary <- models$summary %>%
  set_names(models$id)

(results <- models %>%
  select(type, struct) %>%
  bind_cols(map_dfr(map(models$summary, 'AICtab'), as.list)))
```

```{r}
table_col <- function(mod) {
  tidy_mod <- tidy(mod)
  glance_mod <- glance(mod)
  
  format_est <- function(i) {
    tbl <- tidy_mod %>%
      filter(str_detect(term, i))
    
    if (nrow(tbl) == 0) {
      ''
    } else {
      sig = tbl[['p.value']] < 0.05
      if (is.na(sig) || !sig) {
        sprintf('% 05.3f ', tbl[['estimate']])
      } else {
        sprintf('% 05.3f*', tbl[['estimate']])
      }
    }
  }
  
  format_se <- function(i) {
    tbl <- tidy_mod %>%
      filter(str_detect(term, i))   
    if (nrow(tbl) == 0 || is.na(tbl[['std.error']])) {
      '' 
    } else {
      sprintf('% 05.3f', tbl[['std.error']])
    }
  }
  
  format_mod <- function(i) {
    sprintf('%0.0f', glance_mod[[i]])
  }
  
  mappings <- c(
    `(Intercept)` = '^\\(Intercept\\)',
    `Grade` = '^grade',
    `Approaches to Learning` = '.*F1',
    `Engagement` = '.*F2',
    `Attentional Focusing` = '.*F3',
    `Inhibitory Control` = '.*F4',
    `Attentional Focusing (2)` = '.*F5',
    `sd(Intercept)` = 'sd__\\(Intercept\\)',
    `sd(resid)` = 'sd__Observation'
  )
  
  mappings_glnc <- c(
    `LL` = 'logLik',
    `df` = 'df.residual',
    `AIC` = 'AIC',
    `BIC` = 'BIC'
  )
  
  bind_rows(
    tibble(
      term = names(mappings),
      est = map_chr(mappings, format_est),
      se = map_chr(mappings, format_se)
    ),
    tibble(
      term = names(mappings_glnc),
      est = map_chr(mappings_glnc, format_mod),
      se = ''
    )
  )

}
models %>%
  mutate(tbl_c = map(model, table_col)) %>%
  select(id, tbl_c) %>%
  unnest(tbl_c) %>%
  pivot_longer(-c(id, term), names_to = 'var', values_to = 'val') %>%
  mutate(id = str_c(id, var, sep='.')) %>%
  select(-var) %>%
  pivot_wider(names_from=id, values_from=val) %>%
#  mutate_all(cell_spec, monospace=T) %>%
  set_names(c(' ', rep(c('Estimate', 'SE'), 8))) %>%
  kable(booktabs=T, align=c('l', 'c'), escape=F) %>%
  kable_styling(latex_options = c('scale_down')) %>%
  add_header_above(c(' ' = 1,
                     rep(c('Theory' = 2,
                           '3 Factor' = 2,
                           '4 Factor' = 2,
                           '5 Factor' = 2), 2))
                   )  %>%
  add_header_above(c(' ' = 1, 'Reading' = 8, 'Math' = 8)) %>%
  group_rows(index=c('Fixed Effects' = 7,
                     'Random Effects' = 2,
                     'Model Fit' = 4))
 
```

```{r}
models_summary$read.f4
models_summary$read.theory
```

```{r}
models_summary$math.f4
models_summary$math.theory
```

```{r}
#subset <- sample(unique(df$CHILDID), 40)
subset <- unique(df$CHILDID)

df %>%
  filter(CHILDID %in% subset) %>%
  ggplot(aes(x=grade, y=XMTHETK5, group=CHILDID)) +
  geom_line(alpha=0.9995^(length(subset)))

```

```{r, fig.height=21, fig.width=6}
df %>%
  gather(var, val, XMSCALK5, XRSCALK5, MATL_F1, MENG_F2, MINHIB_F4, MATTEN_F3, XATTNFS_F3, XTCHAPP_F1, XINBCNT_F4) %>%
  ggplot(aes(val)) +
  geom_histogram() +
  facet_wrap(var~grade, scales='free_x', ncol=3)
```
