---
title: "Measurement models for executive function"
author: "Kyle Husmann"
date: "March 25, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

data(eclsk2011)

atl_meas <- c(
  'TKEEPS', 'TSHOWS', 'TWORKS', 'TADAPTS', 'TFOLLOW', 'TPERSIS', 'TATTEN'
)

cbq_meas <- c(
  'TBNOFIN', 'TBGCCLR', 'TBGCBLD', 'TBABSBK',
  'TBEZDAC', 'TBEZDSL', 'TBFLWIN',
  'TBWTTSK', 'TBPLNAC', 'TBTRBST', 'TBAPRRK', 'TBSTNO'
)

meas_dist_plots <- function(df) {
  df %>%
    ggplot(aes(factor(value), fill=!is.na(value))) +
    geom_histogram(stat='count', show.legend = F) +
    facet_grid(vars(occasion), vars(measure)) 
}

missing_plot <- function(df) {
  df %>%
    group_by(occasion, measure) %>%
    summarize(missingness = sum(is.na(value)) / n()) %>%
    ggplot(aes(x=measure, y=missingness)) +
    geom_col() +
    facet_wrap(~occasion)
}

```

```{r, fig.width=10, fig.height=8}
cbq_long <- eclsk2011$study1 %>%
            select(CHILDID, occasion, cbq_meas) %>%
            pivot_longer(cbq_meas, names_to='measure', values_to='value') %>%
            group_by(CHILDID, occasion) %>%
            filter(!all(is.na(value))) %>%
            ungroup()

meas_dist_plots(cbq_long)
missing_plot(cbq_long)
```

```{r, fig.width=10, fig.height=8}
atl_long <- eclsk2011$study1 %>%
            select(CHILDID, occasion, atl_meas) %>%
            pivot_longer(atl_meas, names_to='measure', values_to='value') %>%
            group_by(CHILDID, occasion) %>%
            filter(!all(is.na(value))) %>%
            ungroup() 

meas_dist_plots(atl_long)
missing_plot(atl_long)
```