use-conda: true
cluster-config: cluster.yml
cluster: "qsub -k eo -m n -A {cluster.queue} -l mem={resources.mem_mb}mb -l walltime={resources.walltime_min}:00 -l nodes=1:ppn={threads}"
jobs: 99
latency-wait: 90
